version: '3.7'
services:
    frontend:
        build: frontend/
        entrypoint: vue ui --host 0.0.0.0 --port 8000 --headless
        volumes:
            - ./frontend:/app
        ports:
            - 8000:8000
            - 8080:8080

    api:
        build: api/
        entrypoint: CompileDaemon -log-prefix=false -build="go build" -command="./api"
        ports:
            - "40000:40000"
            - "8081:8081"
        volumes:
            - ./api:/api
            - ./api/_data:/api/_data
        tty: true

    static:
        build: static/
        restart: always
        environment: 
            - VIRTUAL_HOST=i.slacki.io
            - LETSENCRYPT_HOST=i.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./api/uploads:/var/www
            - ./static/nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "127.0.0.1:8082:80"