version: '3.7'
services:
    frontend:
        build: frontend/
        entrypoint: vue ui --host 0.0.0.0 --port 8000 --headless
        volumes:
            - ./frontend:/app
        ports:
            - 8000:8000
            - 8080:8080