version: '3.7'
services:
    frontend:
        image: gcr.io/audio-274519/frontend:v7
        build:
            context: ../frontend
            dockerfile: Dockerfile.production

    api:
        image: gcr.io/audio-274519/api:v9
        build:
            context: ../api
            dockerfile: Dockerfile.production

    static:
        image: gcr.io/audio-274519/static:v4
        build: ../static