version: '3.7'
services:
    frontend:
        image: gcr.io/audio-274519/frontend:v1.0.0
        build:
            context: ../frontend
            dockerfile: Dockerfile.production

    api:
        image: gcr.io/audio-274519/api:v1.0.0
        build:
            context: ../api
            dockerfile: Dockerfile.production

    static:
        image: gcr.io/audio-274519/static:v1.0.0
        build: ../static