# this doesn't block traffic to docker containers that are exposed
# containers have to bind do loopback

- hosts: root
  become: true
  tasks:
  - name: Install iptables-persistent
    apt:
      name: iptables-persistent
      state: present
      update_cache: true
  
  - name: Flush INPUT chain
    command: iptables -F INPUT

  - name: Set loopback rule
    iptables:
      chain: INPUT
      action: append
      in_interface: lo
      jump: ACCEPT
      comment: 'Accept all loop back traffic'
  
  - name: Set established connections rule
    iptables:
      chain: INPUT
      ctstate: 'ESTABLISHED,RELATED'
      jump: ACCEPT
      comment: 'Let all established connection stay'
  
  - name: Set SSH rule
    iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: tcp
      destination_port: 22
      comment: 'Accept SSH traffic'
  
  - name: Allow the server to reply to ping
    iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: icmp
      icmp_type: 0
      comment: "Allow ping"
  
  - name: Allow the server to receive pings
    iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: icmp
      icmp_type: 8
      comment: "Allow ping"
  
  - name: Set HTTP Port 80 HTTP Rule
    iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: tcp
      destination_port: 80
      comment: Allow HTTP
  
  - name: Set HTTP Port 443 SSL Rule
    iptables:
      chain: INPUT
      jump: ACCEPT
      protocol: tcp
      destination_port: 443
      comment: Allow HTTPS
  
  - name: Drop everything else
    iptables:
      chain: INPUT
      jump: DROP
      comment: 'Drop traffic for rules that did not match'
  
  - name: Save iptables
    command: netfilter-persistent save