version: '3.7'

services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        restart: unless-stopped
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy-custom.conf:/etc/nginx/conf.d/proxy-custom.conf:ro
            - certs:/etc/nginx/certs:rw
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        networks:
            - "default"
            - "proxy-tier"
    
    proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        restart: unless-stopped
        environment:
            - NGINX_PROXY_CONTAINER=proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        depends_on:
            - "proxy"
        networks:
            - "default"
            - "proxy-tier"

    # ---    

    api:
        image: gcr.io/audio-274519/api:v7
        container_name: api
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=api.audio.slacki.io
            - LETSENCRYPT_HOST=api.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./_data:/api/_data
            - ./_uploads:/api/_uploads    
        ports:
            - "127.0.0.1:9002:8081"

    frontend:
        image: gcr.io/audio-274519/frontend:v6
        container_name: frontend
        restart: unless-stopped
        environment: 
            - VIRTUAL_HOST=audio.slacki.io
            - LETSENCRYPT_HOST=audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./frontend:/app
        ports:
            - "127.0.0.1:9000:80"

    wwwfrontend:
        image: nginx:stable-alpine
        container_name: wwwfrontend
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=www.audio.slacki.io
            - LETSENCRYPT_HOST=www.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./wwwfrontend.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:9001:80"

    static:
        image: gcr.io/audio-274519/static:v4
        container_name: static
        restart: unless-stopped
        environment: 
            - VIRTUAL_HOST=static.audio.slacki.io
            - LETSENCRYPT_HOST=static.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./_uploads:/var/www
        ports: 
            - "127.0.0.1:9003:80"

volumes:
    certs:
    vhost.d:
    html:
    
networks:
    proxy-tier:
