version: '3.7'

services:
    api:
        image: gcr.io/audio-274519/api:v10
        container_name: api
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=api.audio.slacki.io
            - LETSENCRYPT_HOST=api.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./_data:/api/_data
            - ./_uploads:/api/_uploads    
        ports:
            - "127.0.0.1:9010:8081"

    frontend:
        image: gcr.io/audio-274519/frontend:v9
        container_name: frontend
        restart: unless-stopped
        environment: 
            - VIRTUAL_HOST=audio.slacki.io
            - LETSENCRYPT_HOST=audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        ports:
            - "127.0.0.1:9011:80"

    wwwfrontend:
        image: nginx:stable-alpine
        container_name: wwwfrontend
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=www.audio.slacki.io
            - LETSENCRYPT_HOST=www.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./wwwfrontend.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:9012:80"

    static:
        image: gcr.io/audio-274519/static:v4
        container_name: static
        restart: unless-stopped
        environment: 
            - VIRTUAL_HOST=static.audio.slacki.io
            - LETSENCRYPT_HOST=static.audio.slacki.io
            - LETSENCRYPT_EMAIL=kacperczochara@gmail.com
        volumes:
            - ./_uploads:/var/www
        ports: 
            - "127.0.0.1:9013:80"

