# Build stage
FROM golang AS build-stage
ENV GO111MODULE on
WORKDIR /api
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o api .

# Scratch stage
FROM scratch

ARG DATABASE_CONN
ENV DATABASE_CONN $DATABASE_CONN

COPY --from=build-stage /api/api /api/api
EXPOSE 8081
ENTRYPOINT ["/api/api"]